version: "3.5"

services:
  react:
    image: react
    build:
      context: ./frontend
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    entrypoint: npm start
    env_file:
      - ./common.env
    environment:
      NODE_ENV: compose-dev
      NPM_TOKEN: ${NPM_TOKEN}
      BACKEND: api:3030
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/opt/app
    depends_on:
      - db
      - adminer
      - api
    links:
      - api

  api:
    build:
      context: ./api
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    ports:
      - 3030:3030
    environment:
      NODE_ENV: compose-dev
    env_file:
      - ./common.env
    volumes:
      - ./api:/opt/app

  db:
    image: postgres:10
    env_file:
      - ./common.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    env_file:
      ./common.env
    ports:
      - 8080:8080